/*
 * This file is part of the Illarion Client.
 *
 * Copyright © 2012 - Illarion e.V.
 *
 * The Illarion Client is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * The Illarion Client is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with the Illarion Client.  If not, see <http://www.gnu.org/licenses/>.
 */
package illarion.client.gui;

import de.lessvoid.nifty.Nifty;
import de.lessvoid.nifty.builder.EffectBuilder;
import de.lessvoid.nifty.builder.PanelBuilder;
import de.lessvoid.nifty.controls.label.builder.LabelBuilder;
import de.lessvoid.nifty.elements.Element;
import de.lessvoid.nifty.screen.Screen;
import de.lessvoid.nifty.screen.ScreenController;
import de.lessvoid.nifty.tools.Color;
import illarion.client.net.server.events.ScriptInformReceivedEvent;
import org.apache.log4j.Logger;
import org.bushe.swing.event.EventBus;
import org.bushe.swing.event.EventSubscriber;

/**
 * The task of this handler is to accept and display script informs.
 *
 * @author Martin Karing &gt;nitram@illarion.org&lt;
 */
public final class ScriptInformHandler implements EventSubscriber<ScriptInformReceivedEvent>, ScreenController {
    /**
     * The logger that is used for the logging output of this class.
     */
    private static final Logger LOGGER = Logger.getLogger(ScriptInformHandler.class);

    /**
     * This is a reference to the panel that is supposed to be used as container of the server inform messages.
     */
    private Element parentPanel;

    /**
     * The inform handler that is supposed to display the inform messages generated by this class.
     */
    private final InformHandler informHandler;

    /**
     * Default constructor that prepares the structures needed for this handler to work properly.
     *
     * @param parentHandler the handler that is supposed to display the messages generated in this class
     */
    public ScriptInformHandler(final InformHandler parentHandler) {
        informHandler = parentHandler;
    }

    @Override
    public void bind(final Nifty nifty, final Screen screen) {
        parentPanel = screen.findElementByName("scriptMessagePanel");
    }

    @Override
    public void onEndScreen() {
        EventBus.unsubscribe(ScriptInformReceivedEvent.class, this);
    }

    private static int getDisplayTime(final CharSequence text, final int priority) {
        if (priority == 0) {
            return 5000 + (text.length() * 50);
        }
        return 8000 + (text.length() * 50);
    }

    @Override
    public void onEvent(final ScriptInformReceivedEvent event) {
        if (parentPanel == null) {
            LOGGER.warn("Received script inform before the GUI became ready.");
            return;
        }

        final PanelBuilder panelBuilder = new PanelBuilder();
        panelBuilder.childLayoutHorizontal();

        final LabelBuilder labelBuilder = new LabelBuilder();
        panelBuilder.control(labelBuilder);
        labelBuilder.label(event.getMessage());
        labelBuilder.font("textFont");
        switch (event.getInformPriority()) {
            case 1:
                labelBuilder.color(Color.WHITE);
                break;
            case 2:
                labelBuilder.color(new Color(1.0f, 0.5f, 0.5f, 1.0f));
                break;
            default:
                labelBuilder.color(new Color(0.9f, 0.9f, 0.9f, 1.0f));
        }
        labelBuilder.invisibleToMouse();
        labelBuilder.valignCenter();
        labelBuilder.alignCenter();

        final EffectBuilder moveEffectBuilder = new EffectBuilder("move");
        moveEffectBuilder.length(getDisplayTime(event.getMessage(), event.getInformPriority()));
        moveEffectBuilder.startDelay(0);
        moveEffectBuilder.effectParameter("mode", "toOffset");
        moveEffectBuilder.effectParameter("direction", "bottom");
        moveEffectBuilder.effectParameter("offsetY", "-80");
        labelBuilder.onHideEffect(moveEffectBuilder);

        final EffectBuilder fadeOutBuilder = new EffectBuilder("fade");
        fadeOutBuilder.length(getDisplayTime(event.getMessage(), event.getInformPriority()));
        fadeOutBuilder.startDelay(0);
        fadeOutBuilder.effectParameter("start", "FF");
        fadeOutBuilder.effectParameter("end", "00");
        labelBuilder.onHideEffect(fadeOutBuilder);

        final EffectBuilder fadeOutEffectBuilder = new EffectBuilder("hide");
        fadeOutEffectBuilder.startDelay(getDisplayTime(event.getMessage(), event.getInformPriority()) + 10);
        panelBuilder.onHideEffect(fadeOutEffectBuilder);

        informHandler.showInform(panelBuilder, parentPanel);
    }

    @Override
    public void onStartScreen() {
        EventBus.subscribe(ScriptInformReceivedEvent.class, this);
    }
}
